### ISSUE TITLE
Issue with basicAuth 

### ISSUE THREAD

**Issue by ThinkingAbout** [Baroshem/nuxt-security#125]
Hi
I can't get the basicAuth module to work with server routes (if I uncomment the basicAuth configuration it doesn't work anymore).

nuxt-security: ^0.12.0
nuxt: ^3.2.3

### Reproduction Link

https://stackblitz.com/edit/nuxt-starter-5hyydy?file=nuxt.config.ts,app.vue,package.json

Am I misunderstanding something?
Thank you :)

**Comment by Baroshem** [comment]
Hey, 

thanks for raising this issue. Most probably some kind of backward issue. 

I am taking a look at it right now!

**Comment by Baroshem** [comment]
@ThinkingAbout 

Are you experiencing this problem in the Stackblitz or in a local project?

**Comment by Baroshem** [comment]
The result in the stackblitz is actually the same as if you click cancel on the basic auth popup after enabling it.

It seems like basic auth on stackblitz just does not work like that. Maybe it is because it is embedded?

I just checked this out locally and it works well

**Comment by Baroshem** [comment]
1. I belive that this is the Stackblitz issue that cannot be solved on my module side :(
2. I will check out with the server routes and let you know.
3. This is a bug caused by a recent change here. I will fix it with the point 2.

**Comment by Baroshem** [comment]
@ThinkingAbout 

Could you paste here your example server route that is not working and could you also explain what do you mean by it does not work? The popup does not display?

For the third issue I already have a fix but I am waiting with releasing until fixing the second problem :)

**Comment by Baroshem** [comment]
Thanks for clarification @ThinkingAbout !

I asked this question to Daniel Roe as it seems to me that it can be a Nuxt issue or my maybe I made a mistake somewhere. Will keep you posted :)

**Comment by Baroshem** [comment]
Hey, 

I have added a fix in the 0.13.0 version. Could you check if the problem still persists? Also, you may need to update your code to the latest changes because I needed to ship some potential breaking changes to publish a new functionality.
https://github.com/Baroshem/nuxt-security/releases/tag/v0.13.0

**Comment by ThinkingAbout** [comment]
Hi @Baroshem , I tried to upgrade the version to 0.13.0 but the problem seems to persist. 
If I enable the basicAuth module the calls to my server routes (in server/api/pages) go into 401 Access denied.

Please try playing the stackblitz or in your localhost.

[https://stackblitz.com/edit/nuxt-starter-jdxdof?file=nuxt.config.ts](https://stackblitz.com/edit/nuxt-starter-jdxdof?file=nuxt.config.ts)

Thanks for your help and work,
Matteo

**Comment by Baroshem** [comment]
Ahh I see know clearly. Thanks for the video! I think I know where the problem is. I had a similar one recently with XSS Validation. Tomorrow I will take a look at it once more from a different perspective.

**Comment by Baroshem** [comment]
@ThinkingAbout 

Do you need to use $fetch? I just tried it with `useFetch` instead and it works fine. 

I think with $fetch there is an issue with the order of middlewares getting triggered, or in more detail, how the response from one middleware is passed to another. Your Server Handler seems to be used (at least the req object) to validate basic auth which is not correct because in your request you are not passing the credentials.

**Comment by Baroshem** [comment]
I think this is a bug in Nuxt itself. When using the $fetch I think the event handlers are merged somehow so that your event handler was used to validate basic auth instead of the homepage call. I will talk to the core team about it.

I will also close this issue but feel free to reopen it or open a new one if you find any other bugs or new features ideas :)

Thanks for the quick replies and support in reproduction!
