### ISSUE TITLE
Securing /api/**

### ISSUE THREAD

**Issue by stefanisarie** [Baroshem/nuxt-security#134]
Hey all!

I am having a bunch of endpoints into my /server/api folder and my main concern would be to only allow my front end to consume the data and no one else. Is it possible to achieve this behaviour using nuxt-security? If yes, may I see an example configuration?

Thank you very much!

**Comment by Baroshem** [comment]
Hey, 

You should be able to use the CORS configuration that is coming by default with nuxt-security.

It will set an allowed-origins header to your server url (i.e. localhost:3000) so that only requests that are coming from your frontend (that is on the same domain and port) will be able to use the api endpoints. Other will receive the CORS error that their origin is not in the allowed origins array 

Let me know if that answers your question :)

**Comment by Baroshem** [comment]
But generally, nuxt-security gives you much more than just CORS. 

If you only need CORS and nothing more, you could just use the native H3 cors support. But this would require you to basically create what I have done in the module (a global middleware that would register this CORS handler).

But I recommed to use Nuxt-Security as with it you also get a bunch of useful response headers, XSS validation, Request and Rate Limiters and many more :)

**Comment by Baroshem** [comment]
Hey, you do not even need to register that. I have done this for you in the module. Just register the nuxt-security in modules array and you will get the same thing 😉

Thanks to that, only the request that are coming from your origin (the same host by default) will be accepted and others will be dropped.

For the test, run your application and then in another test application running on a different port, send a request to the first app. You will get the CORS error :)

**Comment by Baroshem** [comment]
Also, the approach of value/route is now deprecated. You can use it the easier way. Check put the docs! :)

**Comment by Baroshem** [comment]
If that worked for you, I think we can close this question. 

Unless there are other questions related to that? :)

**Comment by Don1k1337** [comment]
> Also, if you will have any other questions, do not hesitate to ask them here.
> 
> I am always open for helping and discussions :)

Question about CORS: This can only be executed if the application has the "production" version? Or is it also possible to make some restrictions locally within the CORS Handler rules in nuxt-security module?

Because, in my case, when I making certain rules, as indicated in the CORS documentation, I noticed that in the browser in the "Network" tab, `Access-Control-Allow-Origin: "*"` is the default behavior of the local Nuxt 3 server, or did the module not apply? If this is the default behavior, how can I test the restrictions of requests from another domain? 

Thank you for your response in advance :)
