### ISSUE TITLE
Error when sending FormData

### ISSUE THREAD

**Issue by Droutin** [Baroshem/nuxt-security#147]
### Version

nuxt-security: 0.13.0
nuxt: 3.4.2

### What is actually happening?
Request throws Error when sending formData with file.

``` html
<pre><span class="stack internal">at createError (./node_modules/h3/dist/index.mjs:128:15)</span>
<span class="stack">at Object.handler (./.nuxt/dev/index.mjs:847:17)</span>
<span class="stack internal">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>
<span class="stack internal">at async Object.handler (./node_modules/h3/dist/index.mjs:1247:19)</span>
<span class="stack internal">at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)</span></pre>
```

settings
``` ts
  security: {
    basicAuth: {
      name: "datalangis",
      pass: "strongpass",
      enabled: true,
      message: "test",
    },
    headers: {
      contentSecurityPolicy: false,
      crossOriginEmbedderPolicy: "unsafe-none",
    },
  },
  ```

**Comment by Baroshem** [comment]
Hey, what is the value of this error?

To me, it seems like a XSS validator or requestSizeLimiter issue. You can try to disable them to see if they are causing this problem.

**Comment by Baroshem** [comment]
Hey @Droutin 

Any more details about this issue?

Or preferably the reproduction repository?

**Comment by alexbidenko1998** [comment]
Hello!
I have the same problem and I have discovered that reason is `requestSizeLimiter`.
But there is two more problem:
1. If I disable `requestSizeLimiter` option (make `false` value in `nuxt.config`), I get `[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'throwError')` error message in console when I make request to nuxt api with FormData files.
2. If I update `maxRequestSizeInBytes` and `maxUploadFileRequestInBytes` to any large values, I get the first error (like in issue description).

Some kind of hopeless situation😱

**Comment by alexbidenko1998** [comment]
Hello!

I have the same problem and I have discovered that reason is `xssValidator`. When I disable, the request succeeds.
But there is one more problem:

When I figured out the problem and tried to disable `requestSizeLimiter` option (make `false` value in `nuxt.config`), I got ` [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'throwError')` error message in console when I make request to nuxt api with FormData files.

**Comment by agracia-foticos** [comment]
same issue, we disabled xssValidator: false, and runs

**Comment by Baroshem** [comment]
@agracia-foticos You can disable it for the certain route only so that the validation will be securing your other endpoints while allowing this one endpoint to go without it

**Comment by Baroshem** [comment]
Closing the issue as it can be resolved both globally an per route.
