### ISSUE TITLE
Migrate to Node 18.X

### ISSUE THREAD

**Issue by Baroshem** [Baroshem/nuxt-security#290]

**Comment by Aniketsurya** [comment]
I was using nuxt-security package for nuxt 3 for adding CSP headers and have node 18. It works good on local but while running on azure pipelines it fails stating "[error] Error while requiring module `nuxt-security`: Error: Cannot find module 'C:/Data/Agent/_work/68/s/nuxt-security'"

If there is some other package which can help us to continue please let me know!
Also how it is working okay on local and not on azure pipelines? if there is some solution please let me know!

**Comment by Baroshem** [comment]
Interesting case. Maybe @pi0 will be able to help with that? Is it a known Nitro issue on Azure Pipelines?

**Comment by pi0** [comment]
Can you please provide more info about your pipelines configuration? Usually you should be able to configure Node.js version for building phase.

**Comment by Aniketsurya** [comment]
> Can you please provide more info about your pipelines configuration? Usually you should be able to configure Node.js version for building phase. 

I can configure node version in my pipeline but the issue is as node 16 is deprecated, we have many other dependencies too which are also having issue with node 16. So when I try to run it with node 16 it gives other error.
Better it is to make it work with node 18 but the issue is that it works good and install package of nuxt-security with node 18 on local but not on azure pipeline

**Comment by pi0** [comment]
Ah sorry i thought issue is with using Node 18 in pipelines you are definitely better to use 18 and we will solve any issues if there are 👍🏼 

@Baroshem Any reason `nuxt-security` not supporting Node 18? What is purpose of this issue that you originally created?

**Comment by vejja** [comment]
Looks like we are also having issues with Node 16 in our own CI pipeline.

**Comment by Aniketsurya** [comment]
> Looks like we are also having issues with Node 16 in our own CI pipeline.

Can you please elaborate on the issue which you are facing on your CI pipeline, is it same as I am facing it?

**Comment by vejja** [comment]
> > Looks like we are also having issues with Node 16 in our own CI pipeline.
> 
> Can you please elaborate on the issue which you are facing on your CI pipeline, is it same as I am facing it?

Our pipeline fails because Nuxt 3.8.2 requires globby 14, which only supports Node 18+
Responsible commit was https://github.com/nuxt/nuxt/commit/94b16be9c93c3219c73c790b92111302ea42bfb6
In short Nuxt 3.8.2+ does not support Node 16 anymore

Upgrading CI to Node 18 solves the issue.
So our issue looks different from yours
