### ISSUE TITLE
Loggers are removed in development mode too

### ISSUE THREAD

**Issue by tratteo** [Baroshem/nuxt-security#559]
### Version

nuxt-security: ^2.1.1
nuxt: ^3.14.159

### Reproduction Link

Blank project with removeLoggers set to true:
```ts
security: {
    removeLoggers: true,
}
```
### Steps to reproduce

Set the `removeLoggers` entry to `true` and tun the dev server with `run dev`. I checked that the `NODE_ENV` variable is indeed set to `development`, yet logs are being removed.

### What is Expected?
Expected behaviour is that loggers are **not** removed when the project is in development mode.

### What is actually happening?
Loggers are being removed when running development server with `run dev`.
Even with `NODE_ENV` set to development.

**Comment by vejja** [comment]
That's right @tratteo 
@Baroshem what do you think? Should we have a different default in dev mode?

**Comment by tratteo** [comment]
Hi, well I automatically thought that logs removal was happening solely on production.
I think that generally logs should be enabled in development mode, but if that is an intended feature that's fine.
Thanks for the fast response btw

**Comment by vejja** [comment]
No @tratteo you are actually right, sorry for not being clear in my answer
I'm wondering whether we should always keep logs in dev mode (ie the option is only valid in production mode), or do we allow the option to be set even in dev mode (ie the option is valid in all environments). 
If it's the former, it aligns with the previous behavior; if it's the latter, then we can set it via defaults

**Comment by tratteo** [comment]
Oh sorry. Well probably being able to set the property in dev mode too would be the best.

**Comment by bsiguret** [comment]
Hello guys, I had the same problem before figuring out it was introduced in nuxt-security v2.1. I just conditioned it like that:
`removeLoggers: process.env.NODE_ENV === 'production'`

Maybe changes like that could be more visible (especially when it wasn't set before the PR) because I'm sure we aren't the only ones wondering why console.log wasn't showing. I lost 1 hour on this 😓 

To join the discussion, I don't know why you wouldn't want console.log showing in dev mode so this option is kinda obsolete to me elsewhere than in production. (Maybe to test that it's working well ?)

I'll add that it doesn't work on every component/page for some reason. I can't explain the pattern thought. So this isn't a fully working option, nothing beats a good old eslint no-console rules 😄

**Comment by Baroshem** [comment]
I think that we should always keep logs in development to avoid problems like @bsiguret had :)

**Comment by Baroshem** [comment]
@vejja would you be able to fix it? :)

**Comment by vejja** [comment]
Hi guys
FYI: Just released a hotfix for this
Please upgrade to v2.1.2

**Comment by Baroshem** [comment]
Thanks @vejja ! ❤️
