### ISSUE TITLE
adding custom configuration with array structure results in duplication of header values

### ISSUE THREAD

**Issue by Baroshem** [Baroshem/nuxt-security#78]
When registering a custom configuration like for CSP headers with the array structure as instructed in the docs, user will get a duplicated headers values. This is caused by `defu` package that merges two objects and if they dont find exact match, it will merge two objects together. 

I will instruct in the docs to not use this approach as it will cause bugs.

### Version

nuxt-security: 
nuxt:

**Comment by Baroshem** [comment]
CC @qrzy

**Comment by Qrzy** [comment]
Ouch! 😞  That hurts, I will definitely investigate it!

**Comment by Qrzy** [comment]
It's actually triplication, in case of the default values - it's because in `src/module.ts` we're `defu`ing user options with already `defu`ed defaults along with user options (see: [Nuxt's source](https://github.com/nuxt/framework/blob/5ac9d85a497d6003cbe0c5bbf0e16ef6ea69b46a/packages/kit/src/module/define.ts#L26)) 🙃 
And the multiplication itself comes from the fact that `defu` concats the arrays (see: [defu's README](https://github.com/unjs/defu#remarks)).

My goal with that array approach was to give as much typed hints as possible.
In this case we have two options:
- ditch the array approach (while still having split for certain parts, especially in `contentSecurityPolicy`) and always just accept strings - less hints, defu will be happy, we still should get rid of the additional defu in module definition
- keep the array approach but don't pass the defaults in module definition, so that we have full control over the options merging, using [defu's custom merger](https://github.com/unjs/defu#custom-merger) 

WDYT, @Baroshem ?

**Comment by Baroshem** [comment]
Hey,

Initially, I thought about just letting users know in the docs to use string values. Not the best but will work just fine. I am using this approach. 

But we can think about custom merger as well. I have been thinking about using it for multiple configuration as currently when array is passed, it will create strange objects out of them.

**Comment by Qrzy** [comment]
Alright, I will prepare a PR soon.

**Comment by Qrzy** [comment]
Now, after merging in #80, we still potentially have this issue, if someone definest options both inline and in dedicated config key or use `extends` (see example in https://github.com/Qrzy/nuxt-module-opts-repro), but that's brought up to the Nuxt team here: https://github.com/nuxt/framework/discussions/9904

**Comment by Baroshem** [comment]
Ok, thanks for additional info @Qrzy. Let's keep this issue in the history so that whenever someone will search for it, there will be info about it.
