### ISSUE TITLE
Add securityFile/permissions/additionalHeaders support

### ISSUE THREAD

**Issue by ccxdev** [Baroshem/nuxt-security#98]
Hello, I would like to know if you have any plans to add support for these features:

- security file
- permissions (`geolocation`, `midi`, `payment`, `camera`, etc..)
- additional headers

Also, it would be great, if you export all of types/interfaces from module, for decompose security out of nuxt.config.

**Comment by Baroshem** [comment]
Hey,

Thanks for reaching out!

I am open for any feature requests. Could you please elaborate with each of the points what specifically do you mean and how would you like it to work? I will be happy to answer and implement all those once we agree on the form and need :)

For the types, yes I can export them. I will add it as a part of the documentation improvement so that it will be easier to document the module

**Comment by Baroshem** [comment]
@ccxdev 

Any additional info here?

**Comment by Baroshem** [comment]
Closing the issue as there is no further response from the author about the details.
